spring.application.name=temporal-demo
server.port=8080
app.temporal.address=temporal:7233
app.temporal.namespace=default
app.temporal.workflow-task-queue=file-inspector-workflow
app.temporal.java-activity-task-queue=java-file-inspector
app.temporal.python-activity-task-queue=python-file-inspector
app.shared-files-dir=/shared-files
