package com.docupload.temporal.workflow;

/**
 * Immutable input passed to {@link DocumentProcessingWorkflow#processDocument}.
 *
 * NOTE: Temporal serialises this to JSON via Jackson, so keep it a plain
 * data-carrier with a no-arg constructor and getters/setters.
 *
 * The actual file bytes should NOT be placed here — store them in S3/GCS/MinIO
 * and pass only the {@code storageKey}. Temporal event histories have a size
 * budget (~2 MB per event); large blobs will exceed it.
 */
public class DocumentWorkflowRequest {

    /** Unique job identifier (generated by UploadWorkerController before starting workflow). */
    private String jobId;

    /** Original file name as uploaded by the client. */
    private String originalFileName;

    /** MIME type detected or declared by the client. */
    private String contentType;

    /** File size in bytes — used for progress reporting. */
    private long fileSizeBytes;

    /**
     * Key / path in the object-storage bucket where the raw bytes were staged.
     * Example: "uploads/2025/03/15/{jobId}/original"
     */
    private String storageKey;

    /** ISO-8601 timestamp when the upload was received. */
    private String uploadedAt;

    // ── Constructors ──────────────────────────────────────────────────────────

    public DocumentWorkflowRequest() {}

    public DocumentWorkflowRequest(String jobId, String originalFileName,
                                   String contentType, long fileSizeBytes,
                                   String storageKey, String uploadedAt) {
        this.jobId            = jobId;
        this.originalFileName = originalFileName;
        this.contentType      = contentType;
        this.fileSizeBytes    = fileSizeBytes;
        this.storageKey       = storageKey;
        this.uploadedAt       = uploadedAt;
    }

    // ── Getters / Setters ─────────────────────────────────────────────────────

    public String getJobId()            { return jobId; }
    public void   setJobId(String v)    { this.jobId = v; }

    public String getOriginalFileName()         { return originalFileName; }
    public void   setOriginalFileName(String v) { this.originalFileName = v; }

    public String getContentType()          { return contentType; }
    public void   setContentType(String v)  { this.contentType = v; }

    public long   getFileSizeBytes()          { return fileSizeBytes; }
    public void   setFileSizeBytes(long v)    { this.fileSizeBytes = v; }

    public String getStorageKey()           { return storageKey; }
    public void   setStorageKey(String v)   { this.storageKey = v; }

    public String getUploadedAt()           { return uploadedAt; }
    public void   setUploadedAt(String v)   { this.uploadedAt = v; }
}
