# Temporal Dynamic Configuration — Development defaults
# https://docs.temporal.io/references/dynamic-configuration

system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
    constraints: {}

frontend.enableUpdateWorkflowExecution:
  - value: true
    constraints: {}

frontend.enableUpdateWorkflowExecutionAsyncAccepted:
  - value: true
    constraints: {}
